name: Opal CI/CD

on:
  push:
    branches: [ main, lexerImpl ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure
    
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    
    - name: Check code formatting
      run: |
        find src tests -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | xargs clang-format -style=file -i
        git diff --exit-code || (echo "Code formatting issues found. Run clang-format locally and commit changes." && exit 1)

  release:
    needs: [build, lint]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Package
      run: |
        mkdir -p ${{github.workspace}}/package/opal
        cp -r ${{github.workspace}}/bin/* ${{github.workspace}}/package/opal/
        cp ${{github.workspace}}/README.md ${{github.workspace}}/package/opal/
        cp ${{github.workspace}}/LICENSE ${{github.workspace}}/package/opal/
        cd ${{github.workspace}}/package
        tar -czvf opal-${{ github.event.release.tag_name }}.tar.gz opal
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/package/opal-${{ github.event.release.tag_name }}.tar.gz
        asset_name: opal-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip 