name: Documentation

on:
  push:
    branches: [ main, lexerImpl ]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'Doxyfile'
      - 'scripts/generate_docs.sh'
      - '.github/workflows/docs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz
    
    - name: Generate Documentation
      run: |
        # Use existing documentation generation script
        if [ -f "scripts/generate_docs.sh" ]; then
          echo "Using generate_docs.sh script"
          chmod +x scripts/generate_docs.sh
          ./scripts/generate_docs.sh
        else
          echo "generate_docs.sh script not found, attempting manual generation"
          # Check if Doxyfile exists in root directory
          if [ -f "Doxyfile" ]; then
            doxygen Doxyfile
          # Check if Doxyfile exists in docs directory
          elif [ -f "docs/Doxyfile" ]; then
            doxygen docs/Doxyfile
          else
            echo "Error: Doxyfile not found!"
            exit 1
          fi
        fi
    
    - name: Check HTML output directory
      run: |
        # Check where the generated html directory is located
        if [ -d "docs/html" ]; then
          echo "HTML documentation found in docs/html"
        elif [ -d "html" ]; then
          echo "HTML documentation found in html"
        else
          echo "Searching for all generated html directories:"
          find . -name "html" -type d | sort
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
        force_orphan: true
        full_commit_message: 'docs: update documentation'